### PR TITLE
Changed the render function in template.js to return a string instead of a function.

### PR DESCRIPTION
**Pull request by oosidat**
Updated one instance in src/index.js where url was being treated as a function instead of a string.

All existing tests are passing at this point.

### CODE REVIEW

**Comment by odino** [comment]
I think this is because of the lodash upgrade between v 2 to 3. Which version are you running on your app?

**Comment by oosidat** [comment]
I checked my `node_modules` after doing an `npm install` - the version of lodash is as described in `package.json` - 3.6.0.

**Comment by odino** [comment]
what does `npm list --depth=3` say? Again, this is strange since we had to turn `.url` in a function since its what lodash returns you since version 3 (look for `_.template` [here](https://github.com/lodash/lodash/wiki/Changelog#v300))

**Comment by oosidat** [comment]
Result of `npm list --depth=3`

```
OSIDAT:shisha osidat$ npm list --depth=3
shisha@1.0.0 /Users/osidat/Development/shisha-test/shisha
├── colors@0.6.2
├── http-https@1.0.0
├── lodash@3.6.0
├─┬ mocha@1.21.5
│ ├── commander@2.3.0
│ ├─┬ debug@2.0.0
│ │ └── ms@0.6.2
│ ├── diff@1.0.8
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.6.5
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ └─┬ mkdirp@0.5.0
│   └── minimist@0.0.8
├─┬ mocha-jshint@0.0.9
│ └─┬ jshint@2.8.0
│   ├─┬ cli@0.6.6
│   │ └── glob@3.2.11
│   ├─┬ console-browserify@1.1.0
│   │ └── date-now@0.1.4
│   ├── exit@0.1.2
│   ├─┬ htmlparser2@3.8.3
│   │ ├── domelementtype@1.3.0
│   │ ├── domhandler@2.3.0
│   │ ├── domutils@1.5.1
│   │ ├── entities@1.0.0
│   │ └── readable-stream@1.1.13
│   ├── lodash@3.7.0
│   ├─┬ minimatch@2.0.8
│   │ └── brace-expansion@1.1.0
│   ├── shelljs@0.3.0
│   └── strip-json-comments@1.0.2
├── mockserver@0.8.0
└── yargs@1.3.3
```

**Comment by odino** [comment]
uber weird -- is there any way you could add a test that reproduces the bug?

**Comment by oosidat** [comment]
Other than the existing `'should be able to accept an object made of URLs and status codes'` test, I can't think of anything else.

I should note that I got this error when running `shisha` through command-line, like so: `shisha --domain google.com` where the contents of `.smoke` were:

```
http://{{domain}}/ 302
```

**Comment by odino** [comment]
is there any way you can tar the repo and send it to me? Im pretty curious to see what's  happening

**Comment by oosidat** [comment]
Where should I send it to you?

**Comment by odino** [comment]
you can even attach it here :)

**Comment by oosidat** [comment]
Here you go:

https://gist.github.com/oosidat/693131942f793b725b95

**Comment by odino** [comment]
hey @oosidat you were definitely right, we updated the usage of the lodash templating function but forgot it in the binary, so shisha was broken when using the binary. Your PR looks perfect, gonna merge and create a release now!

**Comment by odino** [comment]
it's  in `1.0.2`

**Pull request merged**
